modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="almosttagged"
version="${file.jarVersion}"
displayName="Almost Tagged"
displayURL="https://github.com/kawaiicakes/AlmostTagged/"
logoFile="almosttagged.png"
credits="Thanks to the Almost Reliable team, ElocinDev for her Json config code, and to Vazkii + wiresegal for their help!"
authors="kawaiicakes"

description='''
An addon for Almost Unified letting preferred items inherit tags.
'''

[[dependencies.almosttagged]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.almosttagged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.almosttagged]]
#    modId="almostreliable"
#    mandatory=true
#    versionRange="[0.5.0,)"
#    ordering="NONE"
#    side="BOTH"