modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="almosttagged"
version="${file.jarVersion}"
displayName="Almost Tagged"
displayURL="https://github.com/kawaiicakes/AlmostTagged/"
logoFile="almosttagged.png"
credits="Thanks to the Almost Reliable team and to Vazkii!"
authors="kawaiicakes"

description='''
'''

[[dependencies.almosttagged]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.almosttagged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
